### ISSUE TITLE
Decouple object names from filenames in the iRODS catalog

### ISSUE THREAD

**Issue by othmar-weber** [irods/irods_resource_plugin_s3#1830]
Since object storage from it's nature is different from POSIX files Systems it has some ugly side effects if files are moved: Each move creates a new objected and an old deleted one. If the objects are to large (in our environment it was 700 MB) then a timeout in the S3 plugin occurs and we have still the old name in the irods catalog but in the S3 bucket I find two objects: One with the old and one with the new name.

I think the major issue is that we treat object storage like a file system which it isn’t. In a file system a move command just updating the inode table. In the case of object storage it means two steps (1st: copy oldname to newname, 2nd: delete oldname).
 
For iRODS just keeping oldname in the storage and changing the entry in the catalog does not solve the problem because if now someone is creating a file in iRODS with oldname (from iRODS user perspective it is not there anymore) you will get an error because this file name still in use by the object storage.
 
The only solution to work around that is to fully decouple the naming of objects in the iRODS catalog and the storage archive resource. That means that an artificial name needs to be created for each object. (There is a performance hint available from AWS: https://aws.amazon.com/blogs/aws/amazon-s3-performance-tips-tricks-seattle-hiring-event/ -> e.g. use a timestamp as object key in reverse order to speed up the lookup).
In that case a rename would not need to be propagated to the archive resource anymore.

**Comment by adetorcy** [comment]
Hi Othmar,

I have a working prototype that uses `reversed_object_id/object_name` as the S3 key name.
```
irods@icat ~> iput -R s3resc VERSION.json 
irods@icat ~> 
irods@icat ~> 
irods@icat ~> ils -L
/tempZone/home/rods:
  rods              0 s3resc;s3cache        10492 2016-05-23.10:03 & VERSION.json
        generic    /tmp/s3cache/home/rods/VERSION.json
  rods              1 s3resc;s3archive        10492 2016-05-23.10:03 & VERSION.json
        generic    /irods-ci/06001/VERSION.json
irods@icat ~> 
irods@icat ~> 
irods@icat ~> imv VERSION.json VERSION.json.bckp
irods@icat ~> 
irods@icat ~> ils -L
/tempZone/home/rods:
  rods              0 s3resc;s3cache        10492 2016-05-23.10:03 & VERSION.json.bckp
        generic    /tmp/s3cache/home/rods/VERSION.json.bckp
  rods              1 s3resc;s3archive        10492 2016-05-23.10:03 & VERSION.json.bckp
        generic    /irods-ci/06001/VERSION.json
irods@icat ~> 
irods@icat ~> 
irods@icat ~> irm -f VERSION.json.bckp
irods@icat ~> 
irods@icat ~> ils -L
/tempZone/home/rods:
irods@icat ~> 
```
How does this look? I will be running some tests with it but wanted to have your feedback on this implementation so far.

**Comment by othmar-weber** [comment]
Hi Antoine,
looks nearly good from my perspective. 

There are some recommendations from AWS how to choose the object names available here: [http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html](url)

It's basically recommended for performance reasons  to choose a key with a high variance at the starting letters. Therefore you should do something with the key to get a greater variance (e.g. put a hash value in front, reverse the number, convert the number to hex and reverse it, ...).

**Comment by adetorcy** [comment]
Hi Othmar,

I reversed the object IDs as per the above [recommendations](http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html#introduce-randomness-reversesequence). The IDs are unique per object so that would provide even greater partitioning than in their example.
If you would prefer to have `<4 character hex hash prefix>/<object_name>` as the S3 key name (or something similar), that can be easily done.

**Comment by othmar-weber** [comment]
Hello Antoine,

I just recognized that I missed the fact that you already reversed the Object-ID. That should be sufficient from my feeling. Does it also make sense to have the iRODS path in the object Name for additional recovery options? Is the Object-ID unique for each physical data object or each iRODS catalog entry?

**Comment by adetorcy** [comment]
Hello Othmar,

The object ID is unique per object and shared by all replicas of that object. Since there can be only one replica per resource that ensures uniqueness on the S3 resource.
I can use the object's logical path after the reversed ID (instead of just the name). Please note though that since S3 keys are decoupled from logical path names, that path might not be relevant anymore if the object is moved. Of course the same can be said about the object name itself.

**Comment by othmar-weber** [comment]
Antoine, 

you are right. The Name Information is not valid after the rename anyway. Therefore it is not necessary to have the path in it. So Object-ID + Original filename should be enough.

**Comment by earlephilhower** [comment]
Looking at the original problem, it seems that this boils down to object rename is slow on AMZ due to object immutability.  If we fix that, via multithreaded, multipart copy (should be running at GB/s++ on any reasonable object store) is this still an issue?  I've got a patch in-progress to implement this, it's not very hard after the multithread/multipart changes were commited.

I think there is a lot of value in having object names == irods path names.  For S3-native apps in the cloud/on-prem which are not using irods, pure read-only access now of datasets is simple and easy.  If we decouple that simple 1:1 mapping this is not possible anymore...

**Comment by adetorcy** [comment]
The decoupling also allows AMZ to better partition S3 data. It is implemented as an optional setting that is set up on a per resource basis.
