### ISSUE TITLE
Upgrade pip to 20.3.4 before installing minio in test hook

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2110]
- [x] main
- [x] 4-2-stable
---
Upgrade pip to 20.3.4 before installing minio in test hook.  This is required to install minio.

**Comment by JustinKyleJames** [comment]
@alanking Do you know what needs to be done for this in main?  Is it just the same changes but with python2 replaced with python3?

Is the minio 6.0.2 version selection still required?

If you don't know I can play around with it and test it out.

**Comment by alanking** [comment]
If things are working as expected in main, then we probably don't need to do anything. I'm guessing we needed to do this in 4-2-stable due to having to support older platforms, but the newer platforms in 4.3.x will have a new enough pip so this isn't an issue. Thoughts?

If agreed, please remove checkboxes (or just remove the "main" checkbox) and close. Thanks!

**Comment by alanking** [comment]
Oops, I guess I could answer the question...

I think that if things aren't working in main, then we just need to upgrade to the latest minio that can be used on all the platforms. In short, no, I don't know what needs to be done for main. :)

**Comment by alanking** [comment]
After some discussion, we decided that we should set 20.3.4 as the *minimum* version and @JustinKyleJames will update #2130 to reflect that.

**Comment by JustinKyleJames** [comment]
I changed it to pip>=20.3.4.  This passed tests.

**Comment by alanking** [comment]
@JustinKyleJames - Please checkbox and close. Thanks!
